object Versions {
    const val coreKtx = "1.13.1"
    const val lifecycleRuntime = "2.8.4"
    const val activityCompose = "1.9.1"
    const val composeBom = "2024.02.00"
    const val junit = "4.13.2"
    const val junitTestExt = "junit:1.2.1"
    const val espressoCore = "3.6.1"
    const val appcompat = "1.7.0"
    const val material = "1.12.0"
    const val hilt = "2.48"
    const val hiltCompiler = "1.2.0"
    const val hiltNavigationCompose = "1.2.0"
    const val retrofit = "2.9.0"
    const val okhttp = "4.12.0"
    const val gsonConverter = "2.9.0"
    const val moshi = "1.13.0"
    const val moshiConverter = "2.9.0"
    const val loggingInterceptor = "4.8.1"
    const val coroutines = "1.3.9"
    const val room = "2.5.1"
    const val coil = "1.4.0"
}